---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: update system
    apt:
      update_cache: true
      upgrade: true

  - name: "install packages"
    package:
      name:
        - tmux
        - openjdk-19-jdk-headless

  - name: "ssh - disable Password Auth"
    lineinfile:
      dest=/etc/ssh/sshd_config
      regexp='^PasswordAuthentication'
      line="PasswordAuthentication no"
      state=present
      backup=yes

  - name: "ssh - disable Root Login"
    lineinfile:
      dest=/etc/ssh/sshd_config
      regexp='^PermitRootLogin'
      line="PermitRootLogin no"
      state=present
      backup=yes

  - name: Reboot the machine
    shell: "sleep 5 && reboot"